baseurl = "https://professor348.github.io/"
languageCode = "en-us"
theme = "archie-solarized"
buildDrafts = false
paginate = 5

pygmentsStyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  mode="toggle"
  useCDN=true
  subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/hcartiaux/hugo-theme-archie-solarized)"
  mathjax = false # enable MathJax support
  katex = true # enable KaTeX support

  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = true

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false
  enableGitInfo = true

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  UpdatedDatePrefix = "Updated"

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default
  [params.contact]
    email = 'dbscoder12@gmail.com'
    phone = '+1 202-555-1212'


[languages]
  [languages.en]
    languageName = "English"
    title = "DanTheCoder"

    [languages.en.params]
      subtitle = "Welcome to my website!"
      owner = ""
      keywords = ""
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "Terminal"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "Home"
          name = "Home"
          url = "/"
          weight = 1
        [[languages.en.menu.main]]
          identifier = "About Me"
          name = "About"
          url = "/about"
          weight = 2
        [[languages.en.menu.main]]
          identifier = "Posts"
          name = "Posts"
          url = "/posts"
          weight = 3